#registration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: na58745874@
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          kakao: # 예시: google, naver, kakao 등
            client-name: Kakao # 예시: Google, Naver, Kakao 등
            client-id: f00f7fb98add05d77fdb20f9843da35b
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # 예시: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: nickname
          naver:
            client-name: Naver
            client-id: XQIdCOgvKzXxrnBhA3Ht
            client-secret: i_y6xvLAEV
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name,email

          google: # 예시: google, naver, kakao 등
            client-name: Google # 예시: Google, Naver, Kakao 등
            client-id: 1046216476104-dknn9ep0hj3eeg70vacr87fot2bspn0v.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google" # 예시: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 예시: https://accounts.google.com/o/oauth2/auth
            token-uri: https://kauth.kakao.com/oauth/token # 예시: https://oauth2.googleapis.com/token
            user-info-uri: https://kapi.kakao.com/v2/user/me # 예시: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: response # 예시: sub (Google의 경우), id (Naver의 경우)
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 예시: https://accounts.google.com/o/oauth2/auth
            token-uri: https://nid.naver.com/oauth2.0/token # 예시: https://oauth2.googleapis.com/token
            user-info-uri: https://openapi.naver.com/v1/nid/me # 예시: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: response # 예시: sub (Google의 경우), id (Naver의 경우)